### ISSUE TITLE
New PRs don't have emoji in title

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#41]
I noticed that PR titles to Github look like `feat: :rocket:  stuff`

instead of

`feat: 🚀  stuff`

**Comment by vivaxy** [comment]
The plain text of the commit is `feat: :rocket: stuff`, and GitHub will display it as `feat: 🚀 stuff`.
If you like to commit the plain text as `feat: 🚀 stuff`, please use the `--emoji emoji` option.

**Comment by ghostsquad** [comment]
@vivaxy what I'm saying though is that github is not displaying the Git PR with the emoji. It's just using the text `:rocket:`. 

![image](https://user-images.githubusercontent.com/903488/75611448-7c65d500-5acf-11ea-85e9-37daba0f5a69.png)

![image](https://user-images.githubusercontent.com/903488/75611458-8be51e00-5acf-11ea-811c-851160993efb.png)

**Comment by vivaxy** [comment]
GitHub displays emoji on commit pages, but not PRs.
![image](https://user-images.githubusercontent.com/4216856/75618162-f2883b80-5ba4-11ea-9534-6b0c7dbbce57.png)

You can use `gacp --emoji emoji` to make commits and PRs all displaying with the emoji. But this will break some old GitLab, because them don't support storing emoji chars in DB.

If you'd like to enable `emoji` option in some projects, you can use the [configuration file](https://github.com/vivaxy/gacp#configuration-file).

**Comment by ghostsquad** [comment]
Thanks for the explanation. I'll try this out.

**Comment by vivaxy** [comment]
You are welcome.
